2016-08-04 20:43:25,941 [Thread-7:18232] [django.request:256] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\git\cms\content\views.py", line 8, in mainpage
    return render(request, 'index.htm', ctx)
  File "C:\Python27\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 46, in get_template
    raise TemplateDoesNotExist(template_name)
TemplateDoesNotExist: index.htm
2016-08-04 20:43:51,032 [Thread-9:18252] [django.request:170] [WARNING]- Not Found: /css/font-awesome.min.css
2016-08-04 20:43:51,032 [Thread-10:17276] [django.request:170] [WARNING]- Not Found: /css/theme.css
2016-08-04 20:43:51,032 [Thread-8:8488] [django.request:170] [WARNING]- Not Found: /css/bootstrap.css
2016-08-04 20:43:51,035 [Thread-11:6136] [django.request:170] [WARNING]- Not Found: /css/prettyPhoto.css
2016-08-04 20:43:51,039 [Thread-12:12300] [django.request:170] [WARNING]- Not Found: /css/zocial.css
2016-08-04 20:43:51,102 [Thread-13:24712] [django.request:170] [WARNING]- Not Found: /css/settings.css
2016-08-04 20:43:51,253 [Thread-14:14176] [django.request:170] [WARNING]- Not Found: /js/jquery.js
2016-08-04 20:43:51,332 [Thread-15:10644] [django.request:170] [WARNING]- Not Found: /js/bootstrap.min.js
2016-08-04 20:43:51,345 [Thread-16:13320] [django.request:170] [WARNING]- Not Found: /js/jquery.themepunch.revolution.min.js
2016-08-04 20:43:51,355 [Thread-17:18472] [django.request:170] [WARNING]- Not Found: /js/jquery.themepunch.plugins.min.js
2016-08-04 20:43:51,371 [Thread-18:21848] [django.request:170] [WARNING]- Not Found: /js/jquery.touchSwipe.min.js
2016-08-04 20:43:51,394 [Thread-19:15240] [django.request:170] [WARNING]- Not Found: /js/jquery.mousewheel.min.js
2016-08-04 20:43:51,483 [Thread-20:14468] [django.request:170] [WARNING]- Not Found: /js/jquery.prettyPhoto.js
2016-08-04 20:43:51,673 [Thread-21:10752] [django.request:170] [WARNING]- Not Found: /js/scripts.js
2016-08-04 20:43:51,686 [Thread-22:10732] [django.request:170] [WARNING]- Not Found: /js/jquery.carouFredSel-6.2.1-packed.js
2016-08-04 20:43:51,710 [Thread-23:18988] [django.request:170] [WARNING]- Not Found: /img/logo.png
2016-08-04 20:43:51,756 [Thread-24:17956] [django.request:170] [WARNING]- Not Found: /img/slider/slider1.jpg
2016-08-04 20:43:51,796 [Thread-25:11484] [django.request:170] [WARNING]- Not Found: /img/slider/robot1.png
2016-08-04 20:43:51,813 [Thread-26:26608] [django.request:170] [WARNING]- Not Found: /img/slider/rocket.png
2016-08-04 20:43:51,950 [Thread-27:26256] [django.request:170] [WARNING]- Not Found: /img/slider/flames.png
2016-08-04 20:43:51,990 [Thread-28:12084] [django.request:170] [WARNING]- Not Found: /img/slider/slider2.jpg
2016-08-04 20:43:52,033 [Thread-29:14004] [django.request:170] [WARNING]- Not Found: /img/slider/iMac.png
2016-08-04 20:43:52,085 [Thread-30:19780] [django.request:170] [WARNING]- Not Found: /img/slider/slider3.jpg
2016-08-04 20:43:52,107 [Thread-31:9432] [django.request:170] [WARNING]- Not Found: /img/slider/robot2.png
2016-08-04 20:43:52,111 [Thread-32:25176] [django.request:170] [WARNING]- Not Found: /img/slider/slider4.jpg
2016-08-04 20:43:52,256 [Thread-33:13608] [django.request:170] [WARNING]- Not Found: /img/small/s1.jpg
2016-08-04 20:43:52,286 [Thread-34:22132] [django.request:170] [WARNING]- Not Found: /img/small/s2.jpg
2016-08-04 20:43:52,326 [Thread-35:20360] [django.request:170] [WARNING]- Not Found: /img/small/s3.jpg
2016-08-04 20:43:52,371 [Thread-36:17660] [django.request:170] [WARNING]- Not Found: /img/small/s4.jpg
2016-08-04 20:43:52,404 [Thread-37:19944] [django.request:170] [WARNING]- Not Found: /img/small/s5.jpg
2016-08-04 20:43:52,414 [Thread-38:3400] [django.request:170] [WARNING]- Not Found: /img/small/s6.jpg
2016-08-04 20:43:52,542 [Thread-39:10396] [django.request:170] [WARNING]- Not Found: /img/small/s7.jpg
2016-08-04 20:43:52,563 [Thread-40:13972] [django.request:170] [WARNING]- Not Found: /img/small/s8.jpg
2016-08-04 20:49:18,585 [Thread-197:8888] [django.request:170] [WARNING]- Not Found: /index.html
2016-08-04 20:53:41,177 [Thread-321:25644] [django.request:170] [WARNING]- Not Found: /contact.html
2016-08-05 14:44:58,701 [Thread-328:18308] [django.request:170] [WARNING]- Not Found: /about.html
2016-08-06 10:47:17,701 [Thread-341:12468] [django.request:170] [WARNING]- Not Found: /services.html
2016-08-06 10:48:32,339 [Thread-387:10872] [django.request:170] [WARNING]- Not Found: /services.html
2016-08-08 13:47:09,138 [Thread-13:9888] [django.request:170] [WARNING]- Not Found: /favicon.ico
2016-08-08 13:57:05,364 [Thread-14:3232] [django.request:170] [WARNING]- Not Found: /team.html
2016-08-08 13:57:10,460 [Thread-15:11828] [django.request:170] [WARNING]- Not Found: /index2.html
2016-08-08 14:50:15,615 [Thread-61:5360] [django.request:256] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\git\cms\content\views.py", line 8, in mainpage
    return render(request, 'index.html', ctx)
  File "C:\Python27\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "C:\Python27\lib\site-packages\django\template\backends\django.py", line 74, in render
    return self.template.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 210, in render
    return self._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 202, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 905, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 113, in render
    compiled_parent = self.get_parent(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 103, in get_parent
    raise TemplateSyntaxError(error_msg)
TemplateSyntaxError: Invalid template name in 'extends' tag: ''. Got this from the 'base.html' variable.
2016-08-08 14:55:21,029 [Thread-140:18744] [django.request:170] [WARNING]- Not Found: /mainpage
2016-08-08 16:16:23,493 [Thread-47:18648] [django.request:256] [ERROR]- Internal Server Error: /tcs/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\git\cms\content\views.py", line 13, in tcs
    return render(request, 'tcs.html', ctx)
  File "C:\Python27\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 46, in get_template
    raise TemplateDoesNotExist(template_name)
TemplateDoesNotExist: tcs.html
2016-08-08 18:31:54,519 [Thread-1739:15952] [django.request:170] [WARNING]- Not Found: /video_gallery.html
2016-08-08 18:39:19,457 [Thread-46:17032] [django.request:170] [WARNING]- Not Found: /mobsolu
2016-08-08 21:09:25,141 [Thread-396:15672] [django.request:170] [WARNING]- Not Found: /favicon.ico
2016-08-09 15:19:20,581 [Thread-48:3700] [django.request:170] [WARNING]- Not Found: /favicon.ico
2016-08-09 15:20:30,737 [Thread-90:14408] [django.request:170] [WARNING]- Not Found: /favicon.ico
2016-08-09 18:10:42,220 [Thread-8:4112] [django.request:170] [WARNING]- Not Found: /css/flexslider.css
2016-08-09 18:10:42,288 [Thread-9:14644] [django.request:170] [WARNING]- Not Found: /css/bootstrap.min.css
2016-08-09 18:10:42,361 [Thread-10:20364] [django.request:170] [WARNING]- Not Found: /css/style.css
2016-08-09 18:10:42,371 [Thread-11:11592] [django.request:170] [WARNING]- Not Found: /js/move-top.js
2016-08-09 18:10:42,378 [Thread-12:1140] [django.request:170] [WARNING]- Not Found: /js/easing.js
2016-08-09 18:10:42,387 [Thread-13:4836] [django.request:170] [WARNING]- Not Found: /js/modernizr.custom.js
2016-08-09 18:10:42,395 [Thread-14:3732] [django.request:170] [WARNING]- Not Found: /css/chocolat.css
2016-08-09 18:10:42,653 [Thread-15:4760] [django.request:170] [WARNING]- Not Found: /js/jquery-2.1.4.min.js
2016-08-09 18:10:42,703 [Thread-16:22020] [django.request:170] [WARNING]- Not Found: /js/bootstrap.min.js
2016-08-09 18:10:42,773 [Thread-17:14432] [django.request:170] [WARNING]- Not Found: /js/jquery.chocolat.js
2016-08-09 18:10:42,805 [Thread-18:20776] [django.request:170] [WARNING]- Not Found: /js/jquery.wmuSlider.js
2016-08-09 18:10:42,809 [Thread-19:25268] [django.request:170] [WARNING]- Not Found: /js/jquery.flexslider.js
2016-08-09 18:10:43,075 [Thread-20:17864] [django.request:170] [WARNING]- Not Found: /images/IMG_3.jpg
2016-08-09 18:10:43,085 [Thread-21:20908] [django.request:170] [WARNING]- Not Found: /images/IMG_1.jpg
2016-08-09 18:10:43,117 [Thread-22:14436] [django.request:170] [WARNING]- Not Found: /images/IMG_5.jpg
2016-08-09 18:10:43,164 [Thread-23:16316] [django.request:170] [WARNING]- Not Found: /images/IMG_2.jpg
2016-08-09 18:10:43,187 [Thread-24:15932] [django.request:170] [WARNING]- Not Found: /images/IMG_4.jpg
2016-08-09 18:10:43,203 [Thread-25:25228] [django.request:170] [WARNING]- Not Found: /images/IMG_6.jpg
2016-08-09 18:10:43,546 [Thread-26:23376] [django.request:170] [WARNING]- Not Found: /images/half-arrow.png
2016-08-09 18:10:43,549 [Thread-27:13348] [django.request:170] [WARNING]- Not Found: /images/twitter.png
2016-08-09 18:10:43,697 [Thread-28:19644] [django.request:170] [WARNING]- Not Found: /favicon.ico
2016-09-05 10:07:12,865 [Thread-67:26880] [django.request:170] [WARNING]- Not Found: /favicon.ico
2016-09-05 10:08:27,673 [Thread-68:2508] [django.request:170] [WARNING]- Not Found: /about.html
2016-09-05 10:08:51,667 [Thread-99:13348] [django.request:170] [WARNING]- Not Found: /gallery.html
2016-09-05 10:16:25,517 [Thread-106:15060] [django.request:170] [WARNING]- Not Found: /index.html
2016-09-05 20:55:40,528 [Thread-13:10992] [django.request:170] [WARNING]- Not Found: /favicon.ico
2016-09-05 20:57:27,595 [Thread-56:2212] [django.request:170] [WARNING]- Not Found: /favicon.ico
2016-09-05 21:20:29,094 [Thread-90:12004] [django.request:170] [WARNING]- Not Found: /index.html
2016-09-05 21:29:05,382 [Thread-159:10584] [django.request:170] [WARNING]- Not Found: /404.html
2016-09-05 21:29:09,644 [Thread-160:10440] [django.request:170] [WARNING]- Not Found: /404.html
2016-09-05 21:29:15,144 [Thread-161:11460] [django.request:170] [WARNING]- Not Found: /gallery.html
2016-09-05 21:42:49,911 [Thread-173:8692] [django.request:170] [WARNING]- Not Found: /gallery.html
2016-09-05 22:07:03,977 [Thread-178:8172] [django.request:170] [WARNING]- Not Found: /about.html
2016-09-09 12:33:48,334 [Thread-13:25448] [django.request:170] [WARNING]- Not Found: /favicon.ico
2016-09-10 14:52:49,618 [Thread-13:28140] [django.request:170] [WARNING]- Not Found: /favicon.ico
2016-09-10 14:52:53,894 [Thread-44:18940] [django.request:170] [WARNING]- Not Found: /favicon.ico
2016-09-10 14:53:02,191 [Thread-45:17288] [django.request:170] [WARNING]- Not Found: /favicon.ico
2016-09-10 14:53:03,309 [Thread-46:25976] [django.request:170] [WARNING]- Not Found: /favicon.ico
2016-09-10 14:53:14,098 [Thread-76:19312] [django.request:170] [WARNING]- Not Found: /favicon.ico
2016-09-10 14:54:01,556 [Thread-78:27352] [django.request:170] [WARNING]- Not Found: /404.html
2016-09-10 15:43:41,160 [Thread-87:21204] [django.request:170] [WARNING]- Not Found: /about.html
2016-09-10 15:43:46,183 [Thread-89:20752] [django.request:170] [WARNING]- Not Found: /404.html
2016-09-10 15:43:49,328 [Thread-88:23344] [django.request:170] [WARNING]- Not Found: /gallery.html
2016-09-10 15:43:51,323 [Thread-90:26696] [django.request:170] [WARNING]- Not Found: /gallery.html
2016-09-10 15:43:53,562 [Thread-92:27624] [django.request:170] [WARNING]- Not Found: /contact.html
2016-09-24 14:15:07,775 [Thread-22:3960] [django.request:170] [WARNING]- Not Found: /favicon.ico
2016-09-27 10:22:55,506 [Thread-4:7604] [django.request:170] [WARNING]- Not Found: /favicon.ico
2016-09-28 10:04:54,430 [Thread-7:8248] [django.request:284] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 123, in get_response
    response = middleware_method(request)
  File "D:\Python27\lib\site-packages\django\middleware\locale.py", line 26, in process_request
    translation.activate(language)
  File "D:\Python27\lib\site-packages\django\utils\translation\__init__.py", line 154, in activate
    return _trans.activate(language)
  File "D:\Python27\lib\site-packages\django\utils\translation\trans_real.py", line 216, in activate
    _active.value = translation(language)
  File "D:\Python27\lib\site-packages\django\utils\translation\trans_real.py", line 205, in translation
    _translations[language] = DjangoTranslation(language)
  File "D:\Python27\lib\site-packages\django\utils\translation\trans_real.py", line 119, in __init__
    self._add_fallback()
  File "D:\Python27\lib\site-packages\django\utils\translation\trans_real.py", line 175, in _add_fallback
    default_translation = translation(settings.LANGUAGE_CODE)
  File "D:\Python27\lib\site-packages\django\utils\translation\trans_real.py", line 205, in translation
    _translations[language] = DjangoTranslation(language)
  File "D:\Python27\lib\site-packages\django\utils\translation\trans_real.py", line 118, in __init__
    raise IOError("No translation files found for default language %s." % settings.LANGUAGE_CODE)
IOError: No translation files found for default language zh-cn.
2016-09-28 10:04:54,576 [Thread-8:4612] [django.request:284] [ERROR]- Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 123, in get_response
    response = middleware_method(request)
  File "D:\Python27\lib\site-packages\django\middleware\locale.py", line 26, in process_request
    translation.activate(language)
  File "D:\Python27\lib\site-packages\django\utils\translation\__init__.py", line 154, in activate
    return _trans.activate(language)
  File "D:\Python27\lib\site-packages\django\utils\translation\trans_real.py", line 216, in activate
    _active.value = translation(language)
  File "D:\Python27\lib\site-packages\django\utils\translation\trans_real.py", line 205, in translation
    _translations[language] = DjangoTranslation(language)
  File "D:\Python27\lib\site-packages\django\utils\translation\trans_real.py", line 119, in __init__
    self._add_fallback()
  File "D:\Python27\lib\site-packages\django\utils\translation\trans_real.py", line 175, in _add_fallback
    default_translation = translation(settings.LANGUAGE_CODE)
  File "D:\Python27\lib\site-packages\django\utils\translation\trans_real.py", line 205, in translation
    _translations[language] = DjangoTranslation(language)
  File "D:\Python27\lib\site-packages\django\utils\translation\trans_real.py", line 118, in __init__
    raise IOError("No translation files found for default language %s." % settings.LANGUAGE_CODE)
IOError: No translation files found for default language zh-cn.
2016-09-28 10:06:02,094 [Thread-37:9176] [django.request:182] [WARNING]- Not Found: /favicon.ico
2016-09-28 11:12:41,572 [Thread-43:10840] [django.request:182] [WARNING]- Not Found: /about.html
2016-09-28 11:12:47,763 [Thread-44:10924] [django.request:182] [WARNING]- Not Found: /404.html
2016-09-28 12:00:34,049 [Thread-1030:10040] [django.request:182] [WARNING]- Not Found: /images/loading.gif
2016-09-28 14:00:18,819 [Thread-243:6576] [django.request:284] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\project\portal_web_en\trunk\content\views.py", line 8, in mainpage
    return render(request, 'index.html', ctx)
  File "D:\Python27\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 96, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 32, in get_template
    return engine.get_template(template_name, dirs)
  File "D:\Python27\lib\site-packages\django\template\backends\django.py", line 40, in get_template
    return Template(self.engine.get_template(template_name, dirs), self)
  File "D:\Python27\lib\site-packages\django\template\engine.py", line 190, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "D:\Python27\lib\site-packages\django\template\engine.py", line 157, in find_template
    name, template_dirs=dirs, skip=skip,
  File "D:\Python27\lib\site-packages\django\template\loaders\base.py", line 46, in get_template
    contents, origin, origin.template_name, self.engine,
  File "D:\Python27\lib\site-packages\django\template\base.py", line 189, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\Python27\lib\site-packages\django\template\base.py", line 231, in compile_nodelist
    return parser.parse()
  File "D:\Python27\lib\site-packages\django\template\base.py", line 516, in parse
    raise self.error(token, e)
TemplateSyntaxError: 'block' tag with name 'our_work' appears more than once
2016-09-28 14:25:33,825 [Thread-698:10292] [django.request:182] [WARNING]- Not Found: /js/jquery.flexslider.js
2016-09-28 14:25:33,842 [Thread-702:8892] [django.request:182] [WARNING]- Not Found: /images/certificate1.png
2016-09-28 14:25:33,992 [Thread-706:5428] [django.request:182] [WARNING]- Not Found: /images/certificate1.png
2016-09-28 14:26:15,371 [Thread-724:10912] [django.request:182] [WARNING]- Not Found: /js/jquery.flexslider.js
2016-09-28 14:27:17,257 [Thread-748:9280] [django.request:182] [WARNING]- Not Found: /js/jquery.flexslider.js
2016-09-28 14:30:52,013 [Thread-876:9372] [django.request:182] [WARNING]- Not Found: /images/certificate1.png
2016-09-28 14:30:52,165 [Thread-880:9960] [django.request:182] [WARNING]- Not Found: /images/certificate1.png
2016-09-28 14:30:53,273 [Thread-884:9124] [django.request:182] [WARNING]- Not Found: /images/certificate1.png
2016-09-28 14:31:20,253 [Thread-904:10592] [django.request:182] [WARNING]- Not Found: /images/certificate1.png
2016-09-28 14:31:20,345 [Thread-908:8844] [django.request:182] [WARNING]- Not Found: /images/certificate1.png
2016-09-28 14:31:20,421 [Thread-912:7720] [django.request:182] [WARNING]- Not Found: /images/certificate1.png
2016-09-28 16:34:22,288 [Thread-3154:8260] [django.request:182] [WARNING]- Not Found: /images/11.jpg
2016-09-28 16:34:22,339 [Thread-3158:9372] [django.request:182] [WARNING]- Not Found: /images/11.jpg
2016-09-28 16:51:28,417 [Thread-4002:10420] [django.request:182] [WARNING]- Not Found: /404.html
2016-09-28 17:00:23,993 [Thread-4044:11380] [django.request:182] [WARNING]- Not Found: /gallery.html
2016-09-28 17:01:37,631 [Thread-4121:11604] [django.request:182] [WARNING]- Not Found: /gallery.html
2016-09-28 17:02:48,585 [Thread-4122:12160] [django.request:182] [WARNING]- Not Found: /gallery.html
2016-09-28 17:03:22,349 [Thread-4128:7112] [django.request:182] [WARNING]- Not Found: /404.html
2016-09-28 17:04:25,003 [Thread-4170:8780] [django.request:182] [WARNING]- Not Found: /index.html
2016-09-28 17:05:07,671 [Thread-4177:7948] [django.request:182] [WARNING]- Not Found: /favicon.ico
2016-09-28 17:05:13,730 [Thread-4178:11920] [django.request:182] [WARNING]- Not Found: /gallery.html
2016-09-28 17:06:27,898 [Thread-4220:11804] [django.request:182] [WARNING]- Not Found: /gallery.html
2016-09-28 17:06:38,453 [Thread-4221:10428] [django.request:182] [WARNING]- Not Found: /gallery.html
2016-09-28 17:07:11,696 [Thread-4262:11588] [django.request:182] [WARNING]- Not Found: /gallery.html
2016-09-28 17:08:49,555 [Thread-4298:12156] [django.request:182] [WARNING]- Not Found: /news.html
2016-09-28 17:09:28,381 [Thread-4299:11252] [django.request:182] [WARNING]- Not Found: /index.html
2016-09-28 17:09:48,951 [Thread-4340:7688] [django.request:182] [WARNING]- Not Found: /404.html
2016-09-29 08:47:20,900 [Thread-37:6732] [django.request:182] [WARNING]- Not Found: /favicon.ico
2016-09-29 09:27:50,993 [Thread-3311:7980] [django.request:182] [WARNING]- Not Found: /favicon.ico
2016-09-29 09:29:20,611 [Thread-3357:1436] [django.request:182] [WARNING]- Not Found: /favicon.ico
2016-09-29 09:35:03,137 [Thread-4070:7020] [django.request:182] [WARNING]- Not Found: /favicon.ico
2016-09-29 10:37:16,783 [Thread-49:6332] [django.request:284] [ERROR]- Internal Server Error: /news
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 123, in get_response
    response = middleware_method(request)
  File "D:\Python27\lib\site-packages\django\middleware\common.py", line 61, in process_request
    if self.should_redirect_with_slash(request):
  File "D:\Python27\lib\site-packages\django\middleware\common.py", line 80, in should_redirect_with_slash
    and urlresolvers.is_valid_path('%s/' % request.path_info, urlconf)
  File "D:\Python27\lib\site-packages\django\core\urlresolvers.py", line 668, in is_valid_path
    resolve(path, urlconf)
  File "D:\Python27\lib\site-packages\django\core\urlresolvers.py", line 534, in resolve
    return get_resolver(urlconf).resolve(path)
  File "D:\Python27\lib\site-packages\django\core\urlresolvers.py", line 376, in resolve
    sub_match = pattern.resolve(new_path)
  File "D:\Python27\lib\site-packages\django\core\urlresolvers.py", line 248, in resolve
    return ResolverMatch(self.callback, args, kwargs, self.name)
  File "D:\Python27\lib\site-packages\django\core\urlresolvers.py", line 255, in callback
    self._callback = get_callable(self._callback_str)
  File "D:\Python27\lib\site-packages\django\utils\lru_cache.py", line 100, in wrapper
    result = user_function(*args, **kwds)
  File "D:\Python27\lib\site-packages\django\core\urlresolvers.py", line 136, in get_callable
    (lookup_view, mod_name))
ViewDoesNotExist: Could not import 'content.views.news'. View does not exist in module content.views.
2016-09-29 10:38:05,358 [Thread-51:5164] [django.request:284] [ERROR]- Internal Server Error: /news
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 123, in get_response
    response = middleware_method(request)
  File "D:\Python27\lib\site-packages\django\middleware\common.py", line 61, in process_request
    if self.should_redirect_with_slash(request):
  File "D:\Python27\lib\site-packages\django\middleware\common.py", line 80, in should_redirect_with_slash
    and urlresolvers.is_valid_path('%s/' % request.path_info, urlconf)
  File "D:\Python27\lib\site-packages\django\core\urlresolvers.py", line 668, in is_valid_path
    resolve(path, urlconf)
  File "D:\Python27\lib\site-packages\django\core\urlresolvers.py", line 534, in resolve
    return get_resolver(urlconf).resolve(path)
  File "D:\Python27\lib\site-packages\django\core\urlresolvers.py", line 376, in resolve
    sub_match = pattern.resolve(new_path)
  File "D:\Python27\lib\site-packages\django\core\urlresolvers.py", line 248, in resolve
    return ResolverMatch(self.callback, args, kwargs, self.name)
  File "D:\Python27\lib\site-packages\django\core\urlresolvers.py", line 255, in callback
    self._callback = get_callable(self._callback_str)
  File "D:\Python27\lib\site-packages\django\utils\lru_cache.py", line 100, in wrapper
    result = user_function(*args, **kwds)
  File "D:\Python27\lib\site-packages\django\core\urlresolvers.py", line 136, in get_callable
    (lookup_view, mod_name))
ViewDoesNotExist: Could not import 'content.views.news'. View does not exist in module content.views.
2016-09-29 11:51:41,928 [Thread-46:8292] [django.request:182] [WARNING]- Not Found: /favicon.ico
2016-09-30 08:58:51,180 [Thread-38:4516] [django.request:182] [WARNING]- Not Found: /favicon.ico
2016-09-30 09:27:42,811 [Thread-374:3052] [django.request:182] [WARNING]- Not Found: /favicon.ico
